services:
  - postgresql
berfor_install:
  - gem install bundler
cache:
  - bundler
before_script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
dist: trusty
language: ruby
rvm:
  - 2.6.5
script:
  - bundle exec rubocop
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: "QTC+k+9GVi1VQuCvGyQfENBtXzvz2nycYaoR8JiDfo4oGGDKwkv7HA+6sH0hTgKlZvAlRgXlgpwbvntdwWTjT9xqU1vs8WAyDlF+vlGTauLOdbGLD2wPtoGZRA5eIUnBlfe6Jks9quY895BwWJPrklwqchPElcyN1+BhELZnwdRFILCjnWQdFFOKxcxa4m3jOUUe18qxtH47Yh+wSn27dTI4jHre1KuoG1HF4HIn3Lzpyy+dbFPt91QmZd+W4l9nS4otLcYWVseW22Rt1af59dG8MP4v0+dYUQwi7Kg5mwbIkw+q4HKvhelqm9WslgTYwK2+doGMh4ZG8TbEbsGl3apArpdYvKUrn+kA4pWp2FaoRgU6WdEKfKS7dBamKnUwrPHjDHZ/3SRmLRUFlLAGirz7C0+Fe1UQDju+v+L4kqxXbPXCDxjW+6/3YzTc622SuOWbnuc5/33HYJhRP7K5HuSr3JajvEbM4FdcTEmuG9GlDfZUKOa7f0dI5yPhFpJc8xgxgPQw25GDgRhGSuHGLZVBYuCUiqPo9Ahaop3+17tKf8ibrYNASNkPEepvZ50XegpUpZtlC9BMoWCxISddWj7I29SKxUEr5RFSQq+sjvkMPjCG0xXTDpN3ZB5VefCltoYFtHpJb3kiT9DK8403LfjLpSIoMJZyZ5RBDI2+MtI="

