services:
  - postgresql
addons:
  postgresql: '9.4'
before_install:
  - gem install bundler
cache:
  - bundler
before_script:
  - bundle install
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - psql -c 'create database instagram_test;' -U postgres
  - bundle exec rails db:create
  - bundle exec rails db:migrate
dist: trusty
language: ruby
rvm:
  - 2.6.5
script:
  - bundle exec rubocop
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: vrohhy2JIjKYhqgFQFoALMvRyjXzxRAg0mxtPx2fRSHq3qqX5NfsCfWbqIzivDtd2azTY0UCn5NQg4DonWU36ENCNelfCRgEE5hF2DexHomV4hdzQNFSg8wQcWN71OTmVXzOmTSIH6zj4+miR2dH/wnFXQT44ge3D729EgW9GuUhuP7/7iAmS95MRL0rw2brn0DQb398wE8ijk3h6P44/7kaBF04x0OEaCsnOPjtKDwC/Wrq65xKBef2M4rHDmW17JS3CRwqdgJJWHcjUQHYYtFsrzwydwSSnQrClXjsCTo1MrBfAGyjRKhyklON3iZ8hJapD8zFE+7LVxIJI8lPk0UStr8d/WQDWHHqi03EctCfzzuj4NYIJiH9fUbMp6Flh/ITJfjT8zh4EbG0EsYm4mAvYMyWC5/3FnGmmY8rrjCTWGAu1Lya2N6B0YaNANco0+iod20Ut6gTfrVHFLypqVpB9xRUZ0l/xi6IFFK6M7wMGq6jC3WhdUaOaFIWUVxFYKp5yUoMmmNbTbMV3SEgDNAxWwcu8OjEBCY9IKcKaFW4RrqKVQiZoGL4Vi/5m7aftRaZDC2H3OK7/aK8d1HeJEpxpBth5uVnVuw4+PD8KqUIWLhD7poOBQgwYVFkdqX5OPGkubBB4f6uOVwdWueA5Sz67flhVtk/gWWrF2X5SP8=
