services:
  - postgresql
addons:
  postgresql: '9.4'
before_install:
  - gem install bundler
  - bundle install
install:
  - nvm install 12
  - npm i -g yarn
  - yarn
cache:
  - bundler
before_script:
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - psql -c 'create database instagram_test;' -U postgres
  - bundle exec rails db:create
  - bundle exec rails db:migrate
dist: trusty
language: ruby
rvm:
  - 2.6.5
script:
  - bundle exec rubocop
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: Ri1SV5y5iuJAdeJwm/WhqruWw6Wu5dkx3aR3/REnL3+Xfgss4VNM2bG/13uwd0ccyTZLSOKYeSZHorHkoSfqV2Pymu/ZbywPMu8Tu+2vY9xpaZRhCwehe/pre1fPqchArW9fwe/Aeb4lt5p9+ZWxxeIMhScuUrCrVe5UcwyK/LkJlh7LY8XXSbsb3qtf6Pnd1ikm3o0YxUz7FrkWBtI8BgeGlsX06A+gmDaFohA4aV/jU6loQz55SlHCjRgCN6oF1aHuXUaOsUC2mjR186/KEpv6qSJEjOuZwE1xNBJfTRBkdyKN1VmnSG5c/gcxHinP9+p2pMeY1ldj8WAdfbo6XIdYdZHnCUqaf11LSXcXOgc1AkL/VqVlI+HkczeQ6P0npV3HRvxfHK1b4idc5+ohgEt4xnPu16R0iK36evXqEKbKLFGGXXs5hAUn3fZR1g8a2utDDmEKwJ7A5pedP7fHHov++JETU6mt+sLsBS1LF1hvu9nKG4+fgg/3/klrFdH1oAvaGxHKG4DFV8g5ZL+fo7f9Oz+6Slj26I8Nz3caXG7M93tAAsn1+kQVBC29Ta1plS8xTjjRVbO2RDAt6o//HVkR5i7BQokfmDebF0MkY0eIc+dZcickXDCxca3gCHUCqNfC5lh/pnvAU3G1/Hk56ZbEvq3wSP6A4eiJozjtd1Y=
